"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Stephen Collings"
email = "stevoland@gmail.com"

[[--scope]]
--when.repositories = ["~/workspace/github.com/eeveebank"]
[--scope.user]
email = "stephen@mettle.co.uk"

[ui]
pager = ["hunk", "pager"]
diff-formatter = ":git"
default-command = ["log", "--limit", "14"]

# merge-editor = "oyui"
diff-editor = "oyui"
diff-instructions = false

[colors]
"diff token" = { underline = false }
"diff removed token" = { bg = "#221111" }
"diff added token" = { bg = "#002200" }

[snapshot]
max-new-file-size = "10MiB"

[revsets]
log = '@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()'

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

# Find commits authored by you
"mine()" = "author(exact:'stephen@mettle.co.uk') | author(exact:'stevoland@gmail.com')"

# View the entire branch being worked on
'slice()' = 'slice(@)'
'slice(from)' = 'ancestors(reachable(from, mutable()), 2)'

# The latest commit on the branch. Works with squash workflow. Use: jj new tip
tip = "exactly(heads(@-::~@), 1)"

# The current set of "open" works. It is defined as: all stacks that are
# reachable from my working copy, or any other commit I wrote.
# n = 1, meaning that nothing from `trunk()` is included, so all resulting
# commits are mutable by definition.
'open()' = 'stack(mine() | @, 1)'

# Returns the closest merge commit to `to`
"closest_merge(to)" = "heads(::to & merges())"

# stack(x, n) is the set of mutable commits reachable from 'x', with 'n'
# parents. 'n' is often useful to customize the display and return set for
# certain operations. 'x' can be used to target the set of 'roots' to traverse,
# e.g. @ is the current stack.
'stack()' = 'stack(@)'
'stack(x)' = 'stack(x, 2)'
'stack(x, n)' = 'ancestors(reachable(x, mutable()), n)'

# [[--scope]]
# --when.repositories = ["~/workspace/github.com/eeveebank"]
# [--scope.revset-aliases]
# # set all remote bookmarks (commits pushed to remote branches) to be immutable
# 'immutable_heads()' = "builtin_immutable_heads() | remote_bookmarks()"

[aliases]
# A truly genius alias from Martin that gracefully lets you do things like type
# 'jj jj log' on the command line without getting a command-not-found error.
jj = []

u = ["undo"]
r = ["redo"]

# Find the closest ancestor with a bookmark pointing at it, and move it to the
# parent of the working copy.
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

fetch = ["git", "fetch"]
# init = ["git", "init", "--colocate"]
mark = ["bookmark", "set", "-r", "@"]
push = ["git", "push"]
track = ["bookmark", "track"]

raf = ["resolve", "--tool", "mergiraf"]
difft = ["diff", "--tool", "difft"]

sync = ['git', 'fetch', '--all-remotes']
evolve = ['rebase', '--skip-empty', '-d', 'master']

long = ["log", "-T", "builtin_log_detailed"]

open = ["log", "-r", "open"]

prek = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj diff $1 $2 --name-only --no-pager | xargs pre-commit run --files",
  "",
]

slice = ["log", "-r", "slice()"]

# https://isaaccorbrey.com/notes/jujutsu-megamerges-for-fun-and-profit
# Inserts the given revset as a new branch under the megamerge.
stack = [
  "rebase",
  "--after",
  "trunk()",
  "--before",
  "closest_merge(@)",
  "--revision",
]

stage = ["stack", "closest_merge(@)+:: ~ empty()"]

restack = [
  "rebase",
  "--onto",
  "trunk()",
  "--source",
  "roots(trunk()..) & stack()",
]

# Retrunk revisions. Typically as `jj retrunk -s ...` -- notably can be used
# with open:
# - jj retrunk -s 'roots(open())'
retrunk = ["rebase", "-d", "trunk()"]

# Retrunk the current stack of work.
reheat = ["rebase", "-d", "trunk()", "-s", "roots(trunk()..stack(@))"]

# 'jj sandwich xyz' to move xyz into the megamerge in parallel to everything
# else. See notes on 'megamerge()' above for how it's resolved.
sandwich = ["rebase", "-B", "megamerge()", "-A", "trunk()", "-r"]

# Take content from any change, and move it into @. The inverse of 'eject'
# - jj consume xyz path/to/file`
consume = ["squash", "--into", "@", "--from"]

# Eject content from @ into any other change. The inverse of 'consume'
# - jj eject xyz --interactive
eject = ["squash", "--from", "@", "--into"]

# EXPERIMENTAL: ultra-generalized command that subsumes both 'diff' and 'show'
examine = ["log", "-T", "builtin_log_detailed", "-p", "-r"]
spice = ["util", "exec", "--", "jj-spice"]

[merge-tools.jj-hunk]
program = "jj-hunk"
edit-args = ["select", "$left", "$right"]

[merge-tools.weave]
program = "weave-driver"
merge-args = [
  "$base",
  "$left",
  "$right",
  "-o",
  "$output",
  "-l",
  "$marker_length",
  "-p",
  "$path",
]
merge-conflict-exit-codes = [1]
merge-tool-edits-conflict-markers = true
conflict-marker-style = "git"

[merge-tools.oyui]
program = "oyui"
edit-args = [
  "-c",
  "/Users/stephen.collings/.config/oyui/config.rn",
  "diff",
  "$left",
  "$right",
]

[templates]
log_node = '''
if(self && !current_working_copy && !immutable && !conflict && in_branch(self),
  "◇",
  builtin_log_node
)
'''
git_push_bookmark = '"stevo/" ++ change_id.short()'

[template-aliases]
# 'format_short_change_id(id)' = 'id.shortest()'
"in_branch(commit)" = 'commit.contained_in("immutable_heads()..bookmarks()")'

# Full timestamp in ISO 8601 format
# 'format_timestamp(timestamp)' = 'timestamp'
# Relative timestamp rendered as "x days/hours/seconds ago"
'format_timestamp(timestamp)' = 'timestamp.ago()'

# Username part of the email address
'format_short_signature(signature)' = 'signature.email().local()'

[remotes.origin]
auto-track-bookmarks = "stevo/*"

[git]
track-default-bookmark-on-clone = true

[fix.tools.oxfmt]
enabled = false
command = ["$root/node_modules/.bin/oxfmt", "--stdin-filepath=$path"]
patterns = [
  "glob:'**/*.ts'",
  "glob:'**/*.tsx'",
  "glob:'**/*.json'",
  "glob:'**/*.md'",
]
